"""Super Admin panel: school deletion, the auto-generated School ID, and status enforcement.

Three behaviours these tests defend:

- A school can actually be deleted. Every School FK is CASCADE, but two of Class's children
  are PROTECT, so a plain delete() blows up on any school that has students or tests.
- The School ID (stored as `School.code`) is generated by the server from the school name,
  never supplied or edited by the client.
- A School's status is a real lever: only an Active school's members can sign in.
"""
from unittest.mock import patch

from django.contrib.auth import get_user_model
from django.test import override_settings
from django.urls import reverse
from rest_framework import status
from rest_framework.test import APITestCase

from apps.schools.models import School
from apps.schools.services import generate_school_id
from apps.students.models import StudentProfile
from apps.tests.models import Test

from .factories import (
    DEFAULT_PASSWORD,
    make_assignment,
    make_chapter,
    make_class,
    make_question,
    make_result,
    make_school,
    make_section,
    make_session,
    make_student,
    make_subject,
    make_test,
    make_user,
)

User = get_user_model()


def populate(school: School) -> None:
    """Give a school the object graph a real one has — the thing that broke deletion."""
    school_class = make_class(school)
    section = make_section(school, school_class)
    subject = make_subject(school, school_class)
    chapter = make_chapter(subject)
    teacher = make_user(User.Role.TEACHER, school)
    student = make_student(school, school_class, section)
    question = make_question(school, subject, chapter, created_by=teacher)
    test = make_test(school, subject, school_class, teacher, questions=[question])
    assignment = make_assignment(test, school_class, teacher)
    make_result(make_session(student, assignment, test))


class SchoolDeletionTests(APITestCase):
    def setUp(self):
        self.csc_admin = make_user(User.Role.CSC_ADMIN, None)
        self.client.force_authenticate(self.csc_admin)

    def test_delete_school_with_students_and_tests_succeeds(self):
        """The regression: PROTECTed Class children made this a hard 500/ProtectedError."""
        school = make_school()
        populate(school)
        school_id = school.id

        resp = self.client.delete(reverse('school-detail', args=[school_id]))

        self.assertEqual(resp.status_code, status.HTTP_204_NO_CONTENT)
        self.assertFalse(School.objects.filter(id=school_id).exists())

    def test_delete_removes_everything_belonging_to_the_school(self):
        school = make_school()
        populate(school)
        school_id = school.id

        self.client.delete(reverse('school-detail', args=[school_id]))

        # The confirm dialog promises the users go too — hold it to that.
        self.assertFalse(User.objects.filter(school_id=school_id).exists())
        self.assertFalse(StudentProfile.objects.filter(school_id=school_id).exists())
        self.assertFalse(Test.objects.filter(school_id=school_id).exists())

    def test_delete_empty_school_still_works(self):
        school = make_school()
        resp = self.client.delete(reverse('school-detail', args=[school.id]))
        self.assertEqual(resp.status_code, status.HTTP_204_NO_CONTENT)

    def test_delete_leaves_other_schools_untouched(self):
        doomed = make_school()
        populate(doomed)
        survivor = make_school()
        populate(survivor)

        self.client.delete(reverse('school-detail', args=[doomed.id]))

        self.assertTrue(School.objects.filter(id=survivor.id).exists())
        self.assertTrue(User.objects.filter(school_id=survivor.id).exists())
        self.assertTrue(Test.objects.filter(school_id=survivor.id).exists())

    def test_school_admin_cannot_delete_their_school(self):
        school = make_school()
        self.client.force_authenticate(make_user(User.Role.SCHOOL_ADMIN, school))

        resp = self.client.delete(reverse('school-detail', args=[school.id]))

        self.assertEqual(resp.status_code, status.HTTP_403_FORBIDDEN)
        self.assertTrue(School.objects.filter(id=school.id).exists())


@override_settings(EMAIL_BACKEND='django.core.mail.backends.locmem.EmailBackend')
class SchoolIdGenerationTests(APITestCase):
    def setUp(self):
        self.csc_admin = make_user(User.Role.CSC_ADMIN, None)
        self.client.force_authenticate(self.csc_admin)
        self.url = reverse('school-list')

    def payload(self, name: str, admin_email: str, **overrides) -> dict:
        data = {
            'name': name,
            'address': '1 Way',
            'city': 'Chennai',
            'state': 'TN',
            'pincode': '600001',
            'official_email': f'office.{admin_email}',
            'contact_phone': '9876543210',
            'admin_full_name': 'An Admin',
            'admin_email': admin_email,
            'status': 'active',
            'school_board': 'cbse',
            'school_code': '33010100101',
        }
        data.update(overrides)
        return data

    def test_school_id_is_global_numeric_sequence(self):
        cases = [
            ('Green Valley School', '001'),
            ('Alpha Public School', '002'),
            ('Bright Future Academy', '003'),
        ]
        for index, (name, expected) in enumerate(cases):
            resp = self.client.post(
                self.url, self.payload(name, f'admin{index}@x.edu'), format='json',
            )
            self.assertEqual(resp.status_code, status.HTTP_201_CREATED)
            self.assertEqual(resp.data['code'], expected)

    def test_client_supplied_code_is_ignored(self):
        resp = self.client.post(
            self.url,
            self.payload('Green Valley School', 'a@x.edu', code='HACKED'),
            format='json',
        )
        self.assertEqual(resp.status_code, status.HTTP_201_CREATED)
        self.assertEqual(resp.data['code'], '001')
        self.assertFalse(School.objects.filter(code='HACKED').exists())

    def test_school_id_cannot_be_edited(self):
        school = make_school(code='001')
        resp = self.client.patch(
            reverse('school-detail', args=[school.id]), {'code': 'CHANGED'}, format='json',
        )
        self.assertEqual(resp.status_code, status.HTTP_200_OK)
        school.refresh_from_db()
        self.assertEqual(school.code, '001')

    def test_generator_ignores_legacy_codes_that_predate_the_scheme(self):
        make_school(code='GREEN-OLD-1', name='Green Legacy School')
        self.assertEqual(generate_school_id('Green Valley School'), '001')


class SchoolStatusTests(APITestCase):
    """Status must actually gate access — otherwise Suspend is a decorative badge."""

    def setUp(self):
        self.school = make_school(status=School.Status.ACTIVE)
        self.admin = make_user(User.Role.SCHOOL_ADMIN, self.school)
        self.login_url = reverse('authentication:login')

    def login(self):
        return self.client.post(
            self.login_url,
            {'email': self.admin.email, 'password': DEFAULT_PASSWORD},
            format='json',
        )

    def test_active_school_member_can_log_in(self):
        self.assertEqual(self.login().status_code, status.HTTP_200_OK)

    def test_suspended_school_blocks_login(self):
        self.school.status = School.Status.SUSPENDED
        self.school.save()

        resp = self.login()

        self.assertEqual(resp.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertIn('suspended', str(resp.data).lower())

    def test_inactive_school_blocks_login(self):
        self.school.status = School.Status.INACTIVE
        self.school.save()

        resp = self.login()

        self.assertEqual(resp.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertIn('inactive', str(resp.data).lower())

    def test_reactivating_a_school_restores_access(self):
        self.school.status = School.Status.SUSPENDED
        self.school.save()
        self.assertEqual(self.login().status_code, status.HTTP_400_BAD_REQUEST)

        self.school.status = School.Status.ACTIVE
        self.school.save()
        self.assertEqual(self.login().status_code, status.HTTP_200_OK)

    def test_students_of_a_suspended_school_are_blocked_too(self):
        school_class = make_class(self.school)
        section = make_section(self.school, school_class)
        student = make_student(self.school, school_class, section, student_id='SUS-0001')
        self.school.status = School.Status.SUSPENDED
        self.school.save()

        resp = self.client.post(
            reverse('authentication:student-login'),
            {'student_id': student.student_id, 'password': DEFAULT_PASSWORD},
            format='json',
        )

        self.assertEqual(resp.status_code, status.HTTP_400_BAD_REQUEST)

    def test_csc_admin_is_never_blocked_by_school_status(self):
        # The CSC Admin has no school and must stay able to sign in and lift a suspension.
        csc_admin = make_user(User.Role.CSC_ADMIN, None)
        self.school.status = School.Status.SUSPENDED
        self.school.save()

        resp = self.client.post(
            self.login_url,
            {'email': csc_admin.email, 'password': DEFAULT_PASSWORD},
            format='json',
        )

        self.assertEqual(resp.status_code, status.HTTP_200_OK)

    def test_status_filter_returns_only_matching_schools(self):
        make_school(status=School.Status.SUSPENDED)
        make_school(status=School.Status.INACTIVE)
        self.client.force_authenticate(make_user(User.Role.CSC_ADMIN, None))

        resp = self.client.get(reverse('school-list'), {'status': 'suspended'})

        self.assertEqual(resp.status_code, status.HTTP_200_OK)
        self.assertTrue(resp.data['count'] >= 1)
        self.assertTrue(all(r['status'] == 'suspended' for r in resp.data['results']))

    def test_google_login_also_respects_school_status(self):
        """Google is a third login door — it must not bypass a suspension."""
        self.admin.oauth_provider = 'google'
        self.admin.oauth_id = 'google-sub-123'
        self.admin.save()
        profile = {'sub': 'google-sub-123', 'email': self.admin.email, 'picture': ''}

        with patch(
            'apps.authentication.views.verify_google_id_token', return_value=profile,
        ):
            # Active school: Google sign-in works.
            ok = self.client.post(
                reverse('authentication:google-login'), {'id_token': 'x'}, format='json',
            )
            self.assertEqual(ok.status_code, status.HTTP_200_OK)

            self.school.status = School.Status.SUSPENDED
            self.school.save()

            blocked = self.client.post(
                reverse('authentication:google-login'), {'id_token': 'x'}, format='json',
            )

        self.assertEqual(blocked.status_code, status.HTTP_403_FORBIDDEN)
        self.assertIn('suspended', str(blocked.data).lower())

    def test_status_must_be_a_valid_choice(self):
        self.client.force_authenticate(make_user(User.Role.CSC_ADMIN, None))
        resp = self.client.patch(
            reverse('school-detail', args=[self.school.id]),
            {'status': 'banana'},
            format='json',
        )
        self.assertEqual(resp.status_code, status.HTTP_400_BAD_REQUEST)
