# Generated by Django 4.2.30 on 2026-05-22 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schools.school'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.class'),
        ),
        migrations.AddField(
            model_name='section',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='schools.school'),
        ),
        migrations.AddField(
            model_name='section',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.class'),
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.school'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='academics.subject'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['school', 'is_active'], name='subjects_school__b445cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school_class', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('school_class', 'name')},
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['school', 'is_active'], name='classes_school__da98b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('subject', 'name')},
        ),
    ]
