# Generated by Django 4.2.30 on 2026-07-14 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='numeric_value',
            field=models.PositiveSmallIntegerField(help_text='1-10 for primary/secondary', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.CheckConstraint(check=models.Q(('numeric_value__gte', 1), ('numeric_value__lte', 10)), name='class_numeric_value_within_supported_grades'),
        ),
    ]
