# Generated by Django 4.2.30 on 2026-08-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_subject_code_autogenerate"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="lessons",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
