# Generated by Django 4.2.30 on 2026-05-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='sub_section_code',
            field=models.CharField(blank=True, choices=[('a', 'a'), ('b', 'b'), ('c', 'c')], help_text='Optional sub-section (a/b/c) for sections A, B, or C only', max_length=1, null=True),
        ),
    ]
