# Generated by Django 4.2.30 on 2026-08-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="lesson",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
