# Generated by Django 4.2.30 on 2026-07-24 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0003_alter_school_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('incorrect_school_name', 'Incorrect School Name'), ('incorrect_login_email', 'Incorrect School Login Email'), ('password_issue', 'Password Issue'), ('other', 'Other')], max_length=40)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20)),
                ('admin_reply', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests_raised', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests_resolved', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to='schools.school')),
            ],
            options={
                'db_table': 'support_requests',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['school', '-created_at'], name='support_req_school__8a9c49_idx'), models.Index(fields=['status', '-created_at'], name='support_req_status_30a1dd_idx')],
            },
        ),
    ]
