# Generated by Django 4.2.30 on 2026-08-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportrequest",
            name="deleted_by_school",
            field=models.BooleanField(default=False),
        ),
    ]
