# Generated by Django 4.2.30 on 2026-07-16 12:49

import re

from django.db import migrations, models

PREFIX_LENGTH = 3


def backfill_teacher_ids(apps, schema_editor):
    """Give teachers that predate this field an ID, so it is populated everywhere.

    Deliberately duplicates the small bit of logic from teachers.services rather than
    importing it: a migration must keep behaving the same even if that service later
    changes, and it can only use historical models.

    Assigns per school in a stable order (oldest teacher first) so a re-run on the same
    data would produce the same IDs.
    """
    TeacherProfile = apps.get_model('teachers', 'TeacherProfile')
    School = apps.get_model('schools', 'School')

    for school in School.objects.all().iterator():
        letters = re.sub(r'[^A-Z]', '', (school.code or '').upper())
        prefix = (letters[:PREFIX_LENGTH] or 'SCH').ljust(PREFIX_LENGTH, 'X') + 'TR_'
        sequence = 0
        for profile in TeacherProfile.objects.filter(
            school=school, teacher_id='',
        ).order_by('id').iterator():
            sequence += 1
            profile.teacher_id = f'{prefix}{sequence:03d}'
            profile.save(update_fields=['teacher_id'])


def clear_teacher_ids(apps, schema_editor):
    """Reverse: blank the IDs so the constraint can be dropped cleanly."""
    TeacherProfile = apps.get_model('teachers', 'TeacherProfile')
    TeacherProfile.objects.update(teacher_id='')


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('schools', '0003_alter_school_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='teacher_id',
            field=models.CharField(blank=True, default='', help_text='Teacher ID — auto-generated from the School ID (e.g. KARTR_001).', max_length=20),
        ),
        # Backfill BEFORE the constraint exists so existing rows can't trip it.
        migrations.RunPython(backfill_teacher_ids, clear_teacher_ids),
        migrations.AddConstraint(
            model_name='teacherprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('teacher_id', ''), _negated=True), fields=('school', 'teacher_id'), name='unique_teacher_id_per_school'),
        ),
    ]
