# Generated by Django 4.2.30 on 2026-07-16 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_limit_classes_to_grade_10'),
        ('teachers', '0002_teacherprofile_teacher_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherassignment',
            name='academic_year',
            field=models.CharField(blank=True, default='', help_text='e.g. "2025-26"', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Optional — class/section assignments made at teacher creation have none.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.subject'),
        ),
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('subject__isnull', True)), fields=('teacher', 'school_class', 'section'), name='unique_class_assignment_per_teacher'),
        ),
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('section__isnull', True), ('subject__isnull', True)), fields=('teacher', 'school_class'), name='unique_whole_class_assignment_per_teacher'),
        ),
    ]
