# Generated by Django 4.2.30 on 2026-07-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_teacherprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='teacher_id',
            field=models.CharField(blank=True, default='', help_text='Teacher ID — auto-generated from the School ID (e.g. KAR_TR_001).', max_length=20),
        ),
    ]
