# Generated by Django 4.2.30 on 2026-08-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0005_alter_teacherprofile_teacher_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="contact_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
