# Generated by Django 4.2.30 on 2026-05-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('exam_start', 'Exam Start'), ('exam_submit', 'Exam Submit'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('data_export', 'Data Export'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deactivated', 'User Deactivated'), ('school_created', 'School Created'), ('school_updated', 'School Updated'), ('result_published', 'Result Published'), ('bulk_import', 'Bulk Import'), ('test_published', 'Test Published'), ('test_assigned', 'Test Assigned')], db_index=True, max_length=40)),
                ('entity_type', models.CharField(blank=True, max_length=50)),
                ('entity_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], default='success', max_length=10)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ('-created_at',),
            },
        ),
    ]
