# Generated by Django 4.2.30 on 2026-06-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('exam_start', 'Exam Start'), ('exam_submit', 'Exam Submit'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('data_export', 'Data Export'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deactivated', 'User Deactivated'), ('school_created', 'School Created'), ('school_updated', 'School Updated'), ('result_published', 'Result Published'), ('bulk_import', 'Bulk Import'), ('test_published', 'Test Published'), ('test_assigned', 'Test Assigned'), ('exam_evaluated', 'Exam Evaluated')], db_index=True, max_length=40),
        ),
    ]
