# Generated by Django 4.2.30 on 2026-05-22 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('time_remaining_seconds', models.IntegerField(help_text='Server-authoritative remaining time. Decremented periodically.')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('abandoned', 'Abandoned')], db_index=True, default='in_progress', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('browser_info', models.CharField(blank=True, max_length=500)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tests.testassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tests.test')),
            ],
            options={
                'db_table': 'exam_sessions',
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, help_text='a/b/c/d, or null if unanswered', max_length=1, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='questions.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examsession')),
            ],
            options={
                'db_table': 'exam_answers',
            },
        ),
        migrations.CreateModel(
            name='AntiCheatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('tab_switch', 'Tab Switch'), ('fullscreen_exit', 'Fullscreen Exit'), ('copy_attempt', 'Copy Attempt'), ('focus_loss', 'Focus Loss')], db_index=True, max_length=30)),
                ('event_count', models.PositiveSmallIntegerField(default=1)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheat_events', to='exams.examsession')),
            ],
            options={
                'db_table': 'anti_cheat_logs',
            },
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['student', 'status'], name='exam_sessio_student_92f366_idx'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['assignment', 'student'], name='exam_sessio_assignm_5ef9fb_idx'),
        ),
        migrations.AddIndex(
            model_name='examanswer',
            index=models.Index(fields=['session'], name='exam_answer_session_f62582_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examanswer',
            unique_together={('session', 'question')},
        ),
        migrations.AddIndex(
            model_name='anticheatlog',
            index=models.Index(fields=['session', 'event_type'], name='anti_cheat__session_18cdae_idx'),
        ),
    ]
