# Generated by Django 4.2.30 on 2026-07-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_rename_contact_email_official_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.CharField(db_index=True, help_text='School ID — auto-generated from the school name (e.g. GRE_001). Not editable.', max_length=20, unique=True),
        ),
    ]
