# Generated by Django 4.2.30 on 2026-08-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0004_add_school_board_and_school_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="School ID — auto-generated numeric sequence (e.g. 001). Not editable.",
                max_length=20,
                unique=True,
            ),
        ),
    ]
