# Generated by Django 4.2.30 on 2026-08-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0005_alter_school_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="lan",
            field=models.CharField(
                blank=True,
                default="",
                help_text="School landline number (LAN).",
                max_length=20,
            ),
        ),
    ]
