# Generated by Django 4.2.30 on 2026-05-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_password_set',
            field=models.BooleanField(default=True, help_text='False when account is provisioned by admin without a password'),
        ),
    ]
