# Generated by Django 4.2.30 on 2026-07-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_add_is_password_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, db_index=True, help_text='Student login ID (students only; null for other roles)', max_length=30, null=True, unique=True),
        ),
    ]
