# Generated by Django 4.2.30 on 2026-07-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='True when the account was given a temporary password that must be changed at next login'),
        ),
    ]
