# Generated by Django 4.2.30 on 2026-07-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('test_assigned', 'Test Assigned'), ('exam_completed', 'Exam Completed'), ('result_published', 'Result Published'), ('system_alert', 'System Alert'), ('reminder', 'Reminder'), ('support_request', 'Support Request')], db_index=True, max_length=30),
        ),
    ]
